---

cdn_organization: "{{ cdn_organization_vault }}"
cdn_activation_key: "{{ cdn_activation_key_vault }}"
# Base network info
_default_domain: "example.ca"

git_configs:
  - name: "user.name"
    scope: "global"
    value: "parmstro@redhat.com"
  - name: "user.email"
    scope: "global"
    value: "parmstro@redhat.com"

environment_hosts:
  - name: "provisioner.{{ _default_domain }}"
    ip: "192.168.140.13"
  - name: "idm.{{ _default_domain }}"
    ip: "192.168.140.5"
  - name: "satellite.{{ _default_domain }}"
    ip: "192.168.140.12"
  - name: "vcenter.{{ _default_domain }}"
    ip: "192.168.140.30"
  - name: "c3esx2.{{ _default_domain }}"
    ip: "192.168.140.32"
  - name: "c3esx3.{{ _default_domain }}"
    ip: "192.168.140.33"
  - name: "c3esx4.{{ _default_domain }}"
    ip: "192.168.140.34"
  - name: "c3esx5.{{ _default_domain }}"
    ip: "192.168.140.35"
  - name: "c3esx6.{{ _default_domain }}"
    ip: "192.168.140.36"

ssh_key_cipher: "ed25519"
ssh_key_file_path: "~/.ssh/id_ed25519"
ssh_public_key_path: "~/.ssh/id_ed25519.pub"

rhah_url: "https://cloud.redhat.com/api/automation-hub/"

rpm_dep_list:
  - ansible-core
  - git
  - vim
  - rhel-system-roles
  - python3
  - python3-ipalib
  - python3-jmespath
  - python3-pip
  - bind-utils

rhis_provisioner_python_modules:
  - ansible-lint

ansible_galaxy_server_list:
  - name: "galaxy_root"
    url: "https://galaxy.ansible.com"
  - name: "automation_hub"
    url: "https://cloud.redhat.com/api/automation-hub/"
    auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
    token: "{{ redhat_automation_hub_token_vault }}"

rhis_repo_path: "~/rhis/"
my_git_username: "<YourGitUserNameHere>"
rhis_git_repos:
  - name: "rhis-builder-idm"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-idm.git"
    force: true
  - name: "rhis-builder-satellite"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-satellite.git"
    force: true
  - name: "rhis-builder-aap"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-aap.git"
    force: true
  - name: "rhis-builder-pipelines"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-pipelines.git"
    force: true
  - name: "rhis-builder-nbde"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-nbde.git"
    force: true
  - name: "rhis-builder-day-2-ops"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-day-2-ops.git"
    force: true
  - name: "rhis-builder-ansible-ee"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-ansible-ee.git"
    force: true
  - name: "rhis-builder-imagebuilder"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-imagebuilder.git"
    force: true
