---

# These are examples of settings for your convenience.
# This is our default ssh user
# You will be installing all the repos, ssh keys, etc.. into this users home directory
# This user will have privilege escalation capability.
rhis_user: "ansiblerunner"

# ssh key location information for creating the rhis_user connection to the provisioner
ssh_key_cipher: "ed25519"                     # not_secret
ssh_key_file_path: "~/.ssh/id_ed25519"        # not_secret
ssh_public_key_path: "~/.ssh/id_ed25519.pub"  # not_secret

# These values are used to register the provisioner to the CDN
default_organization_id: "{{ default_organization_id_vault }}"
provisioner_activation_key: "{{ provisioner_activation_key_vault }}"
