---

# The rpm requirements for rhis-builder-provisioner
rpm_requirements_list:
  - ansible-core
  - git
  - vim
  - rhel-system-roles
  - python3
  - python3-ipalib
  - python3-jmespath
  - python3-pip
  - bind-utils

# WARNING: WE *WILL* OVERWRITE /etc/ansible/ansible.cfg
# we will back it up with the current iso8601basic datetimestamp
# provisioner galaxy configuration
rhah_refresh_token: "{{ redhat_automation_hub_token_vault }}"
rhah_refresh_token_cmd: "{{ automation_hub_refresh_token_cmd_vault }}"

# This helps us when dealing with the git repositories for rhis-builder-*
git_configs:
  - name: "user.name"
    scope: "global"
    value: "parmstro"
  - name: "user.email"
    scope: "global"
    value: "parmstro@redhat.com"

# Use this value to provide a default domain name
# for network variables that use the domain
# it simplifies updates for environment
# alternately, you can override in the domain in individual variables.
_default_domain: "example.ca"

# If we are starting from zero and do not have DNS configured yet. e.g. IdM will be our DNS
# We use these values to update the local /etc/hosts file on the provisioner, idm and satellite
# bootstrap systems so that we have basic name resolution for the bootstrap process
environment_hosts:
  - name: "provisioner.{{ _default_domain }}"
    ip: "192.168.140.13"
  - name: "idm.{{ _default_domain }}"
    ip: "192.168.140.5"
  - name: "satellite.{{ _default_domain }}"
    ip: "192.168.140.12"

  # You can extend this e.g. if you want to add your VMware environment
  # Development environment subnet
  - name: "vcenter.{{ _default_domain }}"
    ip: "192.168.140.30"
  - name: "c3esx2.{{ _default_domain }}"
    ip: "192.168.140.32"
  - name: "c3esx3.{{ _default_domain }}"
    ip: "192.168.140.33"
  - name: "c3esx4.{{ _default_domain }}"
    ip: "192.168.140.34"
  - name: "c3esx5.{{ _default_domain }}"
    ip: "192.168.140.35"
  - name: "c3esx6.{{ _default_domain }}"
    ip: "192.168.140.36"

rhis_repo_path: "~/rhis/"
my_git_username: "{{ git_configs[0].value }}"
rhis_git_repos:
  - name: "rhis-builder-idm"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-idm.git"
    force: true
  - name: "rhis-builder-satellite"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-satellite.git"
    force: true
  - name: "rhis-builder-aap"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-aap.git"
    force: true
  - name: "rhis-builder-pipelines"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-pipelines.git"
    force: true
  - name: "rhis-builder-nbde"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-nbde.git"
    force: true
  - name: "rhis-builder-day-2-ops"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-day-2-ops.git"
    force: true
  - name: "rhis-builder-ansible-ee"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-ansible-ee.git"
    force: true
  - name: "rhis-builder-imagebuilder"
    url: "https://github.com/{{ my_git_username }}/rhis-builder-imagebuilder.git"
    force: true

vault_file_remote_path: "~/.ansible/vault"
