---
# These are the collections required by the rhis-builder-*
# You can limit these to the particular repos you are configuring if you want to`

collections:
  - name: ansible.controller
    version: "<4.6"               # When building for AAP 2.4
#  - name: ansible.controller
#    version: ">=4.6"             # When building for AAP 2.5
  - name: "ansible.netcommon"
  - name: "ansible.posix"
  - name: "ansible.utils"
  - name: "azure.azcollection"
  - name: "community.general"
  - name: "community.vmware"
  - name: "community.aws"
  - name: "containers.podman"
  - name: "redhat.rhel_idm"
  - name: "redhat.rhel_system_roles"
  - name: "redhat.satellite"
  - name: "redhat.satellite_operations"
