---

# BugHunterCredit: Ben Blasco

# Problem: Parsing and local/remote issues when trying to preserve ansible.cfg
# are a total PITA. We eventually want to capture the provisioner configuration anyway. So...

# Solution: We are simply going to force the ansible config on the provisioner.
# If you want to ensure that you have everything in your ansible.cfg file that you need.
# Update the roles/provisioner_pre/tasks/templates/ansible.cfg.j2 template
- name: "Backup the ansible configuration on the provisioner"
  ansible.builtin.copy:
    src: "/etc/ansible/ansible.cfg"
    dest: "/etc/ansible/ansible.cfg.{{ ansible_date_time.iso8601_basic }}.bkp"
    mode: "0644"
    owner: root
    group: root
    remote_src: true

- name: "Create the rhis-builder ansible configuration on the provisioner"
  ansible.builtin.template:
    src: "ansible.cfg.j2"
    dest: "/etc/ansible/ansible.cfg"
    mode: "0644"
    owner: root
    group: root

- name: "Ensure the automation hub token is refreshed."
  ansible.builtin.command: "{{ rhah_refresh_token_cmd }}"
  register: refresh_token_result
  changed_when: refresh_token_result.rc == 0

# Much, much cleaner, simpler and maintainable for everyone. :-)
