---

# Parsing the remote ini file is a pain.
# Lets copy the file locally to a temporary location and use lookup.
# If it looks good proceed, if not warn the user to check the provisioner.

# BugHunterCredit: Ben Blasco

# Need to determine whether we are running on the provisioner or the users laptop
# if on the provisioner, run local
# if on your laptop, do not run local

- name: "Ensure there is no local evaluation file"
  connection: local
  ansible.builtin.file:
    path: "~/rhis-evaluate-ansible.cfg"
    state: "absent"

- name: "Fetch the remote ansible config to evaluate it."
  ansible.builtin.fetch:
    src: "/etc/ansible/ansible.cfg"
    dest: "~/rhis-evaluate-ansible.cfg"
    flat: true

# Lookup always evaluates on the machine where playbook execution is launched
- name: "Get the list of galaxy server entries"
  ansible.builtin.set_fact:
    server_list: "{{ lookup('ansible.builtin.ini', 'server_list', section='galaxy', file='~/rhis-evaluate-ansible.cfg') | split(',') | trim }}"

- name: "Get the list of urls for the entries"
  ansible.builtin.set_fact:
    urls: "{{ urls | default([]) + [lookup('ansible.builtin.ini', 'url', section='galaxy_server.' + section_name, file='~/rhis-evaluate-ansible.cfg')] }}"
  loop: "{{ server_list }}"
  loop_control:
    loop_var: section_name

- name: "Assert that the automation hub url is in the list"
  ansible.builtin.assert:
    that: rhah_url in urls
    fail_msg: "Could not find automation hub url. Please check ansible.cfg on the remote machine. (localfile: ~/rhis-evaluate-ansible-cfg/ansible.cfg)"

- name: "Clean up"
  connection: local
  ansible.builtin.file:
    path: "~/rhis-evaluate-ansible.cfg"
    state: "absent"
