---

- name: "Evaluate ssh capability to the provisioner node"
  block:

    - name: "Try to ssh as the rhis-builder user to the provisioner from the provisioner using a key"
      ansible.builtin.command: "ssh {{ rhis_user }}@{{ ansible_fqdn }} -o PasswordAuthentication=no -o StrictHostKeyChecking=accept-new -o RemoteCommand='echo Killroy_was_here'"  # noqa yaml[line-length]
      register: result
      changed_when: result.rc == 0
      become: false

    - name: "Assert we were there"
      ansible.builtin.assert:
        that: result.stdout == "Killroy_was_here"
      become: false

  rescue:
    - name: "Unable to ssh as rhis-builder user - configuring ssh access"
      ansible.builtin.debug:
        msg: "Please configure passwordless ssh on the provisioner node"
